---
- name: Remove source for custom packages
  when:
    - builder_custom_repos is defined
    - not builder_custom_repos_persist | default(false)
  block:
    - name: Loop through the repos to debug them
      ansible.builtin.debug:
        var: __builder_repo
      loop: "{{ builder_custom_repos }}"
      loop_control:
        loop_var: __builder_repo
    - name: Loop through the repos and configure them
      infra.osbuild.repository:  # noqa only-builtins
        repo_name: "{{ __builder_repo['name'] }}"
        base_url: "{{ __builder_repo['base_url'] }}"
        type: "{{ __builder_repo['type'] | default('yum-baseurl') }}"
        check_ssl: "{{ __builder_repo['check_ssl'] | default(true) }}"
        check_gpg: "{{ __builder_repo['check_gpg'] | default(true) }}"
        gpgkey_urls: "{{ __builder_repo['gpgkey_urls'] | default(omit) }}"
        rhsm: "{{ __builder_repo['rhsm'] | default(false) }}"
        state: "absent"
      loop: "{{ builder_custom_repos }}"
      loop_control:
        loop_var: __builder_repo
      notify:
        - __clear_osbuild_composer_package_cache

- name: Remove source for additional RHSM packages
  when:
    - __builder_rhsm_repos_info['rhsm_info'] is defined
  block:
    - name: Loop through the repos to debug them
      ansible.builtin.debug:
        var: __builder_rhsm_repo
      loop: "{{ __builder_rhsm_repos_info['rhsm_info'] }}"
      loop_control:
        loop_var: __builder_rhsm_repo
    - name: Loop through the repos and configure them
      vars:
        rhc_repositories:
          - {name: "{{ __builder_rhsm_repo['name'] }}", state: disabled}
      # notify:
      #  - __clear_osbuild_composer_package_cache
      ansible.builtin.include_role:
        name: fedora.linux_system_roles.rhc
      loop: "{{ __builder_rhsm_repos_info['rhsm_info'] }}"
      loop_control:
        loop_var: __builder_rhsm_repo

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
