---
archive_path_template: changelogs/archive/{version}
changelog_filename_template: ../CHANGELOG.rst
changelog_filename_version_depth: 0
changes_file: changelog.yaml
changes_format: combined
flatmap: disable
ignore_other_fragment_extensions: true
is_other_project: false
keep_fragments: false
mention_ancestor: true
notesdir: fragments
prelude_section_name: release_summary
prelude_section_title: Release Summary
prevent_known_fragments: true
sanitize_changelog: true
sections:
  - - major_changes
    - Major Changes
  - - minor_changes
    - Minor Changes
  - - breaking_changes
    - Breaking Changes / Porting Guide
  - - deprecated_features
    - Deprecated Features
  - - removed_features
    - Removed Features (previously deprecated)
  - - security_fixes
    - Security Fixes
  - - bugfixes
    - Bugfixes
  - - known_issues
    - Known Issues
title: Infra.Osbuild
trivial_section_name: trivial
use_fqcn: true
