---

- name: Get Package Facts
  ansible.builtin.package_facts:

- name: Setup Repositories
  community.general.rhsm_repository:
    state: enabled
    purge: true
    name:
      - "rhel-{{ ansible_distribution_major_version }}-for-x86_64-appstream-rpms"
      - "rhel-{{ ansible_distribution_major_version }}-for-x86_64-baseos-rpms"
  when:
    - ansible_distribution == 'RedHat'
    - '"rh-amazon-rhui-client" not in ansible_facts["packages"]'
    - '"rhui-azure-rhel9" not in ansible_facts["packages"]'
    - '"rhui-azure-rhel8" not in ansible_facts["packages"]'
  

- name: Install Packages
  ansible.builtin.dnf:
    state: present
    name:
      - rsync
      - osbuild-composer
      - composer-cli
      - cockpit-composer
      - bash-completion
      - firewalld
      - genisoimage
      - httpd
      - syslinux
      - cockpit

- name: RHEL8, CentOS8 and Fedora32 =< specific setup
  when:
    - ansible_distribution in ['RedHat', 'CentOS', 'Fedora']
    - ansible_distribution == 'Fedora' and ansible_distribution_major_version|int < 33 or
      ansible_distribution_major_version|int == 8
  block:
    - name: Install pytoml
      ansible.builtin.dnf:
        state: present
        name:
          - python3-pytoml

- name: RHEL9, CentOS9 and Fedora33 => specific setup
  block:
    - name: Install toml
      ansible.builtin.dnf:
        state: present
        name:
          - python3-toml
  when:
    - ansible_distribution in ['RedHat', 'CentOS', 'Fedora']
    - ansible_distribution == 'Fedora' and ansible_distribution_major_version|int > 32 or
      ansible_distribution_major_version|int == 9

- name: Enable Cockpit/Composer/Firewalld/Apache
  ansible.builtin.systemd:
    state: started
    enabled: true
    name: "{{ item }}"
  loop:
    - osbuild-composer.socket
    - cockpit.socket
    - httpd.service
    - firewalld

- name: Enable Firewall Ports for Cockpit/Composer/Apache
  ansible.posix.firewalld:
    permanent: true
    immediate: true 
    service: "{{ item }}"
    state: enabled
  loop:
    - cockpit
    - http

- name: Add source for custom packages
  when:
    - custom_repo_name
  osbuild.composer.repository:
    repo_name: "{{ custom_repo_name }}"
    base_url: "{{ custom_repo_base_url | default(omit) }}"
    type: "{{ custom_repo_type | default(omit) }}"
    check_ssl: "{{ custom_repo_check_ssl | default(omit) }}"
    check_gpg: "{{ custom_repo_check_gpg | default(omit) }}"
    gpgkey_urls: "{{ gpgkey_urls | default(omit) }}"
    state: "{{ custom_repo_state }}"
